---
language: python
python:
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements.txt
script:
    - make check
    - make generate
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
