---
language: python
python:
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements.txt
    - sudo apt-get install -y pandoc
script:
    - make check
    - make generate
deploy:
    provider: pages
    token: $GITHUB_TOKEN
    local_dir: build/
    skip_cleanup: false
    keep_history: true
    on:
        branch: master
