---
language: python
python:
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements.txt
    - apt-get install pandoc
script:
    - make check
    - make generate
deploy:
    provider: pages:git
    token: $GITHUB_TOKEN
    cleanup: false
    keep_history: true
    on:
        branch: master
