---
dist: bionic
language: python
python:
    - "3.7"
install:
    - make setup
script:
    - make lint
    - make check
    - make generate
deploy:
    provider: pages
    token: $GITHUB_TOKEN
    local_dir: site/
    skip_cleanup: true
    keep_history: true
    on:
        branch: master
