#!/usr/bin/env python

"""
Analyse batch S-I-R simulation.
"""

import argparse
import h5py
from read_from_file import dataset_map


def _analyse(h5file, output_file, beta_list, gamma_list):
    """
    Write statistics on infections from batch simulations to asciidoc table.
    """
    def get_max(dataset):
        return 100 * max(dataset['infected'])

    dataset_map(h5file, output_file, beta_list, gamma_list, get_max)


def analyse():
    """
    Analyse sub-command.
    """
    parser = argparse.ArgumentParser(description="Run the table generator.")
    parser.add_argument('filename')
    parser.add_argument('output_filename', nargs='?', default='')
    default = range(10, 100, 10)
    parser.add_argument('--beta', default=default, type=list)
    parser.add_argument('--gamma', default=default, type=list)
    args = parser.parse_args()
    with h5py.File(args.filename, 'r') as h5file:
        _analyse(h5file, args.output_filename, args.beta, args.gamma)


if __name__ == "__main__":
    analyse()
