#!/usr/bin/env python

"""
Analyse batch S-I-R simulation.
"""

import argparse
from read_from_file import read_from_files


def _analyse(name, output_file, beta_list, gamma_list):
    """
    Write statistics on infections from batch simulations to asciidoc table.
    """
    def get_max(file):
        return max(file['data/infected'])

    read_from_files(name, output_file, beta_list, gamma_list, get_max)


def analyse():
    """
    Analyse sub-command.
    """
    parser = argparse.ArgumentParser(description="Run the table generator.")
    parser.add_argument('filename')
    parser.add_argument('output_filename', nargs='?', default='')
    parser.add_argument('--beta',
                        default=range(10, 100, 10), type=list)
    parser.add_argument('--gamma',
                        default=range(10, 100, 10), type=list)
    args = parser.parse_args()
    _analyse(args.filename, args.output_filename, args.beta, args.gamma)


if __name__ == "__main__":
    analyse()
