#!/usr/bin/env python

"""
Plot the duration of an epidemic.
"""

import argparse
import h5py
from read_from_file import read_from_files


def _duration(filename, output_filename, beta, gamma):
    """
    Duration of each situation.
    """
    def get_duration(file):
        infected = file['data/infected']
        index = next((i for i in range(0, 365) if infected[i] < 1.0))
        if index:
            return file['data/time'][index]
        return file['data/time'][-1]

    read_from_files(filename, output_filename, beta, gamma, get_duration)


def duration():
    """
    Get the duration of all the batches.
    """
    desc = "Get the duration of an epidemic"
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('filename')
    parser.add_argument('output_filename')
    parser.add_argument('--beta', default=range(10, 100, 10), type=list)
    parser.add_argument('--gamma', default=range(10, 100, 10), type=list)
    args = parser.parse_args()
    _duration(args.filename, args.output_filename, args.beta, args.gamma)


if __name__ == "__main__":
    duration()
