#!/usr/bin/env python

"""
Plot results from a S-I-R simulation.
"""

import argparse
import matplotlib.pyplot as plt
import h5py


def _plot(input_filename, output_filename):
    """
    Plot the time-series in output_filename.
    """
    output_file = h5py.File(input_filename, 'r')

    data = output_file.get('data')
    time = data.get('time')[...]
    susceptible = data.get('susceptible')
    infected = data.get('infected')
    recovered = data.get('recovered')

    fig = plt.figure()
    fig.set_size_inches(10, 5)
    plt.plot(time, susceptible[...])
    plt.plot(time, infected[...])
    plt.plot(time, recovered[...])
    plt.legend(['Susceptible', 'Infected', 'Recovered'])
    plt.ylabel('Percent of Population [%]')
    plt.xlabel('Time [days]')
    if not output_filename:
        plt.show()
    else:
        plt.savefig(output_filename)


def plot():
    """
    Run the plot command.
    """
    desc = "Plot results from a S-I-R simulation"
    plot_parser = argparse.ArgumentParser(description=desc)
    plot_parser.add_argument('input')
    plot_parser.add_argument('output', nargs='?', default='')
    plot_args = plot_parser.parse_args()
    _plot(plot_args.input, plot_args.output)


if __name__ == "__main__":
    plot()
