#!/usr/bin/env python

"""
The Susceptible - Infectious - Recovered (SIR) model.

See index.html#sir
"""

from sys import argv
import argparse
import numpy
import matplotlib.pyplot as plt
import h5py
from read_from_file import read_from_files


def _batch(name, beta_list, gamma_list):
    """
    Run batch simulations for all combinations of beta_list and gamma_list.
    """
    for beta in beta_list:
        for gamma in gamma_list:
            beta_int = int(round(beta * 100))
            gamma_int = int(round(gamma * 100))
            _simulate(f'{name}_{beta_int}_{gamma_int}.h5',
                      beta=beta, gamma=gamma)


def batch():
    """
    Batch sub-command.
    """
    parser = argparse.ArgumentParser(description="Run the batch simulations")
    parser.add_argument('filename')
    parser.add_argument('--beta',
                        default=numpy.arange(0.1, 1.0, 0.1), type=list)
    parser.add_argument('--gamma',
                        default=numpy.arange(0.1, 1.0, 0.1), type=list)
    args = parser.parse_args(argv[2:])
    _batch(args.filename, args.beta, args.gamma)


def _simulate(output_filename, **kwargs):
    """
    Run a SIR simulation.
    """
    S = 99.0
    I = 1.0
    R = 0.0
    N = S + I + R
    B = kwargs.get('beta', 0.04)
    g = kwargs.get('gamma', 0.01)
    T = 0
    dt = 1.0

    tt = [T]
    ss = [S]
    ii = [I]
    rr = [R]

    it = 0
    for it in range(0, 365):
        # Compute the rates.
        dS = -B * I * S / N
        dI = B * I * S / N - g * I
        dR = g * I

        # Compute the values at the next time.
        T += dt
        S += dt * dS
        I += dt * dI
        R += dt * dR

        # Store the values for analysis.
        tt.append(T)
        ss.append(S)
        ii.append(I)
        rr.append(R)

    with h5py.File(output_filename, 'w') as output_file:
        data = output_file.create_group(u"data")
        data.attrs[u"beta"] = B
        data.attrs[u"gamma"] = g
        time = data.create_dataset(u"time", data=numpy.array(tt))
        time.attrs[u"units"] = u'days'
        susc = data.create_dataset(u'susceptible', data=numpy.array(ss))
        susc.attrs[u"units"] = u'percent'
        ifcd = data.create_dataset(u'infected', data=numpy.array(ii))
        ifcd.attrs[u"units"] = u'percent'
        rcvd = data.create_dataset(u'recovered', data=numpy.array(rr))
        rcvd.attrs[u"units"] = u'percent'
        output_file.flush()


def simulate():
    """
    Simulate sub-command.
    """
    parser = argparse.ArgumentParser(description="Run the simulation")
    parser.add_argument('filename')
    parser.add_argument('--beta', default=0.04, type=float)
    parser.add_argument('--gamma', default=0.01, type=float)
    args = parser.parse_args(argv[2:])
    _simulate(args.filename, beta=args.beta, gamma=args.gamma)


def main():
    """
    Parse the input command to determine which ont to run.
    """
    parser = argparse.ArgumentParser(description="Simulate the S-I-R model.",
                                     usage='''sir <command> [args]

The commands are:
  simulate  Run a simulation
  batch     Run a batch of simulations''')
    parser.add_argument('command', help="The command to run")
    args = parser.parse_args(argv[1:2])
    globals()[args.command]()


if __name__ == "__main__":
    main()
