#!/usr/bin/env python

"""
Get the total number of infections from a batch S-I-R simulation.
"""

import argparse
import h5py
from read_from_file import dataset_map


def _total(h5file, output_filename, beta_list, gamma_list):
    """
    Total number of infections.
    """
    def get_max(dataset):
        return 100 * dataset['recovered'][-1]

    dataset_map(h5file, output_filename, beta_list, gamma_list, get_max)


def total():
    """
    Total sub-command.
    """
    parser = argparse.ArgumentParser(
        description="Get the total number of infections.")
    parser.add_argument('filename')
    parser.add_argument('output_filename')
    parser.add_argument('--beta', default=range(10, 100, 10), type=list)
    parser.add_argument('--gamma', default=range(10, 100, 10), type=list)
    args = parser.parse_args()
    with h5py.File(args.filename, 'r') as h5file:
        _total(h5file, args.output_filename, args.beta, args.gamma)


if __name__ == "__main__":
    total()
